### ISSUE TITLE
Crash on OCIHandleFree?

### ISSUE THREAD

**Issue by Deniskore** [quietboil/sibyl#3]
Hi @quietboil !
I create an asynchronous session pool like it says in the documentation, I get a crash after a few hours of running the application.
I tried the latest version of the Instant Client(21.6), nothing has changed.

Oracle Linux 7.9
Oracle Instant Client 19.14
Rust 1.60

```
#0  0x00007ffff6aebbeb in kpufhndl0 ()
   from /usr/lib/oracle/19.14/client64/lib/libclntsh.so.19.1
#1  0x000055555569e456 in drop<sibyl::oci::OCIAuthInfo> (self=<optimized out>)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/sibyl-0.6.5/src/oci/handle.rs:41
#2  0x000055555569e456 in {closure#0} ()
#3  poll<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}, core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>> (self=..., _cx=<optimized out>)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/blocking/task.rs:42
#4  {closure#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>> (
    ptr=0x7fffec5a1230)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/core.rs:165
#5  with_mut<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>, core::task::poll::Poll<core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>>, tokio::runtime::task::core::{impl#3}::poll::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>> (self=0x7fffec5a1230, f=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/loom/std/unsafe_cell.rs:14
#6  poll<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>> (
    self=0x7fffec5a1230, cx=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/core.rs:155
#7  {closure#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>> ()
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/harness.rs:470
#8  call_once<core::task::poll::Poll<core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>>
    (
    self=<error reading variable: access outside bounds of object referenced via synthetic pointer>, _args=<optimized out>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271
#9  do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>>, core::task::poll::Poll<core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>>> (data=<optimized out>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492
#10 try<core::task::poll::Poll<core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>>> (
    f=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456
#11 catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>>>, core::task::poll::Poll<core::result::Result<sibyl::oci::ptr::Ptr<sibyl::oci::OCISvcCtx>, sibyl::err::Error>>> (
    f=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137
#12 poll_future<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>> (
    core=0x7fffec5a1230, id=..., cx=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/harness.rs:458
#13 poll_inner<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>, tokio::runtime::blocking::schedule::NoopSchedule> (self=<optimized out>)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/harness.rs:104
#14 poll<tokio::runtime::blocking::task::BlockingTask<sibyl::pool::session::nonblocking::{impl#0}::get_svc_ctx::{async_fn#0}::{closure_env#0}>, tokio::runtime::blocking::schedule::NoopSchedule> (self=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/harness.rs:57
#15 tokio::runtime::task::raw::poll::hca9ee028b9323cee (ptr=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/raw.rs:144
#16 0x0000555555a81ec4 in poll (self=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/raw.rs:84
#17 run<tokio::runtime::blocking::schedule::NoopSchedule> (self=...)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/task/mod.rs:413
#18 run (
    self=<error reading variable: access outside bounds of object referenced via synthetic pointer>)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/blocking/pool.rs:91
#19 run (self=0x555555cd8e80, worker_thread_id=17)
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/blocking/pool.rs:325
#20 {closure#0} ()
    at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.1/src/runtime/blocking/pool.rs:300
#21 std::sys_common::backtrace::__rust_begin_short_backtrace::h0e1d582b13e6ce95
    (f=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122
#22 0x0000555555a8a568 in {closure#0}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()> ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:498
#23 call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()>> (self=..., _args=<optimized out>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271
#24 do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()>>, ()> (data=<optimized out>)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492
#25 try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()>>> (f=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456
#26 catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()>>, ()> (f=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137
#27 {closure#1}<tokio::runtime::blocking::pool::{impl#4}::spawn_thread::{closure_env#0}, ()> ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:497
#28 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h7e3d63f4cbc3f99a ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227
#29 0x0000555555a70bf5 in call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853
#30 call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853
#31 std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9 ()
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c//library/std/src/sys/unix/thread.rs:108
#32 0x00007ffff344bea5 in start_thread () from /lib64/libpthread.so.0
#33 0x00007ffff7b0b9fd in clone () from /lib64/libc.so.6```

**Comment by Deniskore** [comment]
I didn't get a crash for 12 hours, 20k requests in total.
I think the new version fixed the issue.
